// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl1_AU6LP5guWoUvqhirG5x5h2W05ZxBU',
    appId: '1:530557070947:web:c4e5f6g7h8i9j0k1l2m3n4o5',
    messagingSenderId: '530557070947',
    projectId: 'madrasa-570c9',
    authDomain: 'madrasa-570c9.firebaseapp.com',
    storageBucket: 'madrasa-570c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1_AU6LP5guWoUvqhirG5x5h2W05ZxBU',
    appId: '1:530557070947:android:00943dc5171792cfb39256',
    messagingSenderId: '530557070947',
    projectId: 'madrasa-570c9',
    storageBucket: 'madrasa-570c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:530557070947:ios:XXXXXXXXXXXXXXXX',
    messagingSenderId: '530557070947',
    projectId: 'madrasa-570c9',
    storageBucket: 'madrasa-570c9.firebasestorage.app',
    iosBundleId: 'com.madrash.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:530557070947:ios:XXXXXXXXXXXXXXXX',
    messagingSenderId: '530557070947',
    projectId: 'madrasa-570c9',
    storageBucket: 'madrasa-570c9.firebasestorage.app',
    iosBundleId: 'com.madrash.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl1_AU6LP5guWoUvqhirG5x5h2W05ZxBU',
    appId: '1:530557070947:web:c4e5f6g7h8i9j0k1l2m3n4o5', // نفس web appId
    messagingSenderId: '530557070947',
    projectId: 'madrasa-570c9',
    authDomain: 'madrasa-570c9.firebaseapp.com',
    storageBucket: 'madrasa-570c9.firebasestorage.app',
  );
}
